# Project Name
TARGET = DaisyGuitar

# Sources
CPP_SOURCES = DaisyGuitar.cpp

# Library Locations
# Adjust these paths if your libDaisy/DaisySP are located elsewhere
# Now relative to: /dp/firmware/
LIBDAISY_DIR ?= ../../../libDaisy
DAISYSP_DIR ?= ../../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
